### ISSUE TITLE
Allow searching archives for groups

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup-core#44]
Either through publicising the `searching` tool, or adding functions to the Archive prototype, I think there should be more options to reliably search archives for groups, for example based on their title.

To get a group with the title 'bob' in another project, I had to do this:

    let groups = archive.getGroups();
    let group = groups.filter((g) => g._remoteObject.title === 'bob')[0];

This clearly isn't a reliable or clean way to do it. I would much rather be able to do:

    let group = Buttercup.tools.searching.findGroupByTitle(archive.getGroups(), 'bob');

Or, better yet:

    let group = archive.findGroupByTitle('bob');

**Comment by Jameskmonger** [comment]
I'd be more than happy to address this in a PR if you can decide on the solution @perry-mitchell

**Comment by perry-mitchell** [comment]
This is a very interesting topic.. I definitely agree that we need to add this functionality.

The reason I had not exposed the searching tools is because they operate on the composed, raw JSON data behind the archive (searching commands don't return ManagedGroup or ManagedEntry instances). For this reason, I'd like to keep it hidden for now.

What are your thoughts on having a couple of Archive-level functions like `findGroups` and `findEntries`? We'd need to figure our exactly how the methods would work, as groups have just a title, but entries have properties and meta.

What about:
 * `findGroupsByTitle(title)` - Searches for groups that contain `title`
 * `findEntriesByProperty(propName, value)`
 * `findEntriesByMeta(metaName, value)`

That way we could search by several different aspects - This could be used in the GUI's search field at some stage in the future too. Perhaps returning an array of matched items would be better too, as you could just `Array.shift()` them to get the first.

**Comment by perry-mitchell** [comment]
I might take this @Jameskmonger if you're on other items. Would like to get this out this week :)

**Comment by Jameskmonger** [comment]
Feel free @perry-mitchell.

I agree that the best solution would be to return an array of matching items rather than the first, and then letting the user work with those.
